--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

-- Started on 2025-05-29 19:10:25

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4850 (class 1262 OID 16852)
-- Name: articles; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE articles WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'French_France.1252';


ALTER DATABASE articles OWNER TO postgres;

\connect articles

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 25150)
-- Name: articles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.articles (
    id bigint NOT NULL,
    content character varying(255),
    publication_date character varying(255),
    title character varying(255)
);


ALTER TABLE public.articles OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 25149)
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 25158)
-- Name: comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comments (
    article_id bigint,
    id bigint NOT NULL,
    comment character varying(255)
);


ALTER TABLE public.comments OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 25157)
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4842 (class 0 OID 25150)
-- Dependencies: 216
-- Data for Name: articles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.articles VALUES (1, ' The pandemic accelerated a global shift to remote work. While some companies are returning to office spaces, many are embracing hybrid or fully remote models.', '2024-09-15', 'The Rise of Remote Work: Is the Office Dead?');
INSERT INTO public.articles VALUES (2, ' Artificial Intelligence is revolutionizing diagnostics and patient care, but concerns about data privacy and ethical use are rising.', '2025-01-04', 'AI in Healthcare: Promise and Peril');
INSERT INTO public.articles VALUES (3, ' Unlike previous generations, Gen Z prioritizes work-life balance, mental health, and meaningful careers over traditional success markers.', '2025-03-21', 'Why Gen Z is Redefining Success');
INSERT INTO public.articles VALUES (4, 'Cities worldwide are adapting infrastructure to combat rising temperatures and extreme weather, integrating sustainability into development.', '2024-11-30', 'Climate Change and Urban Planning: A Critical Intersection');
INSERT INTO public.articles VALUES (5, ': With e-learning platforms and virtual classrooms booming, traditional education is being reshaped for the digital age.', ' 2025-02-10', 'The Future of Education: Beyond the Classroom');
INSERT INTO public.articles VALUES (6, ' Bitcoin continues to experience dramatic price swings, making it both a risky investment and a potential opportunity for savvy traders.', '2025-04-08', 'Bitcoin’s Volatility: Risk or Opportunity?');
INSERT INTO public.articles VALUES (7, ' Private spaceflight companies are opening space tourism to civilians—but the price tag remains out of reach for most.', ' 2025-05-01', 'Space Tourism: The Next Frontier or Just for the Rich?');


--
-- TOC entry 4844 (class 0 OID 25158)
-- Dependencies: 218
-- Data for Name: comments; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.comments VALUES (7, 1, 'good article');


--
-- TOC entry 4851 (class 0 OID 0)
-- Dependencies: 215
-- Name: articles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.articles_id_seq', 7, true);


--
-- TOC entry 4852 (class 0 OID 0)
-- Dependencies: 217
-- Name: comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comments_id_seq', 1, true);


--
-- TOC entry 4694 (class 2606 OID 25156)
-- Name: articles articles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);


--
-- TOC entry 4696 (class 2606 OID 25162)
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- TOC entry 4697 (class 2606 OID 25163)
-- Name: comments fkk4ib6syde10dalk7r7xdl0m5p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkk4ib6syde10dalk7r7xdl0m5p FOREIGN KEY (article_id) REFERENCES public.articles(id);


-- Completed on 2025-05-29 19:10:26

--
-- PostgreSQL database dump complete
--

